[package]
name = "bsd-getopt"
version = "0.1.2"
edition = "2024"

description = "A minimal BSD-style getopt implementation in Rust"
license = "BSD-2-Clause"
repository = "https://github.com/Numbchenchen/bsd-getopt"
readme = "README.md"
keywords = ["getopt", "cli", "argument", "parser", "unix"]
categories = ["command-line-interface"]

[dependencies]
